name: adescrow_app
description: Escroc App

publish_to: "none"

version: 1.4.1+6

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  # manually added dependency
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: 6.2.1
  country_code_picker: ^3.0.0
  get_storage: ^2.1.1
  logger: 2.4.0
  pin_code_fields: ^8.0.1
  intl: 0.19.0
  http: 1.2.2
  path_provider: 2.1.4
  path: ^1.8.3
  mime:
  image_picker: 1.1.2
  file_picker: 8.1.2
  flutter_svg: 2.0.10+1
  flutter_spinkit: ^5.2.0
  cached_network_image: 3.4.1
  dotted_decoration: ^2.0.0
  flutter_inappwebview: 6.1.5
  flutter_animate: 4.5.0
  connectivity_plus: 6.0.5
  flutter_pdfview: 1.3.3
  local_auth: 2.3.0

  permission_handler:
  device_info_plus: 11.0.0
  dropdown_button2:
  qr_flutter: ^4.1.0
  lottie:
#  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
#  flutter_launcher_icons: 0.13.1
#  change_app_package_name: 1.3.0
#  build_runner:
#  flutter_gen_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_launcher.jpg"
#
#flutter_gen:
#  output: lib/custom_assets/ # Optional (default: lib/gen/)
#  line_length: 80 # Optional (default: 80)
##  flutter packages pub run build_runner build
##  fluttergen -c pubspec.yaml  # only for mac

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/placeholder/
