/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();
  static const String PLUGIN_NAME = 'adescrow_app';
  static const String PLUGIN_VERSION = '1.4.1+6';
}
